### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Superhuman07** [akoscz/YouTubePlaylist#12]
Hi i am running your app on my device and using my api key it force closes and has this error in the lines:-
`FATAL EXCEPTION: main
                                                                    Process: com.akoscz.youtube, PID: 27594
                                                                    Theme: themes:{}
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.google.api.services.youtube.model.PlaylistListResponse.getItems()' on a null object reference
                                                                        at com.akoscz.youtube.YouTubeRecyclerViewFragment$1.onPostExecute(YouTubeRecyclerViewFragment.java:98)
                                                                        at com.akoscz.youtube.YouTubeRecyclerViewFragment$1.onPostExecute(YouTubeRecyclerViewFragment.java:93)
                                                                        at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                        at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Can you provide solution to this error?

Update :- I learned from one of the issues from your profile that the app needs **browser key** please update your **readme**.

**Comment by akoscz** [comment]
Hi @Superhuman07. Using a Browser key is good for development as a quick solution.  But ultimately if you're going to deploy your app to the Google Play Store you should use an Android key built with the release key of your app.

As for the NPE, that's a bug.  It should not crash.  I will get that fixed in a couple of days when I have some time.  Thanks for the report.

**Comment by Superhuman07** [comment]
Ok cool! Thanks for the reply.

**Comment by akoscz** [comment]
Re-opening issue so that I don't forget to fix the NPE :)

**Comment by goodlifechris** [comment]
Its nort really working the nullpointer error exists any help

**Comment by thoinv** [comment]
You must use "Browser API key" (Server key)  because execute() method is part of java client api and not Android Client API
